[project]
name = "ecofeast"
version = "2.0.0"
requires-python = "~=3.13.0"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
testpaths = ["tests"]
python_files = ["test_*.py"]
filterwarnings = ["ignore::DeprecationWarning"]

[tool.black]
line-length = 120
target-version = ["py313"]
include = '\.py$'
extend-exclude = '''
/(
  migrations/
  ml_service/models/
  staticfiles/
  env/
  venv/
  .env/
)/
'''

[tool.isort]
profile = "black"
line_length = 120
skip = ["migrations", "ml_service/models", "staticfiles", "venv", "env"]

[tool.coverage.run]
omit = ["*/migrations/*", "*/tests/*", "*/staticfiles/*", "manage.py"]
